import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Cursor } from "@/components/cursor";
import Navbar from "@/components/modules/layout/navbar";
import StarsAnimation from "@/components/stars-animation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Cursor />
        <StarsAnimation />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
